/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cbcalla.avrokafkaexample.models.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Rx extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5763033321823007394L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Rx\",\"namespace\":\"com.cbcalla.avrokafkaexample.models.avro\",\"fields\":[{\"name\":\"rxId\",\"type\":\"string\"},{\"name\":\"rxNbr\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"patientId\",\"type\":\"int\",\"default\":0},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"RxStatus\",\"symbols\":[\"ACTIVE\",\"CANCELLED\",\"TRANSFERRED\",\"ON_HOLD\",\"DEACTIVATED\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Rx> ENCODER =
      new BinaryMessageEncoder<Rx>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Rx> DECODER =
      new BinaryMessageDecoder<Rx>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Rx> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Rx> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Rx> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Rx>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Rx to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Rx from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Rx instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Rx fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence rxId;
   private java.lang.CharSequence rxNbr;
   private int patientId;
   private com.cbcalla.avrokafkaexample.models.avro.RxStatus status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Rx() {}

  /**
   * All-args constructor.
   * @param rxId The new value for rxId
   * @param rxNbr The new value for rxNbr
   * @param patientId The new value for patientId
   * @param status The new value for status
   */
  public Rx(java.lang.CharSequence rxId, java.lang.CharSequence rxNbr, java.lang.Integer patientId, com.cbcalla.avrokafkaexample.models.avro.RxStatus status) {
    this.rxId = rxId;
    this.rxNbr = rxNbr;
    this.patientId = patientId;
    this.status = status;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return rxId;
    case 1: return rxNbr;
    case 2: return patientId;
    case 3: return status;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: rxId = (java.lang.CharSequence)value$; break;
    case 1: rxNbr = (java.lang.CharSequence)value$; break;
    case 2: patientId = (java.lang.Integer)value$; break;
    case 3: status = (com.cbcalla.avrokafkaexample.models.avro.RxStatus)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'rxId' field.
   * @return The value of the 'rxId' field.
   */
  public java.lang.CharSequence getRxId() {
    return rxId;
  }


  /**
   * Sets the value of the 'rxId' field.
   * @param value the value to set.
   */
  public void setRxId(java.lang.CharSequence value) {
    this.rxId = value;
  }

  /**
   * Gets the value of the 'rxNbr' field.
   * @return The value of the 'rxNbr' field.
   */
  public java.lang.CharSequence getRxNbr() {
    return rxNbr;
  }


  /**
   * Sets the value of the 'rxNbr' field.
   * @param value the value to set.
   */
  public void setRxNbr(java.lang.CharSequence value) {
    this.rxNbr = value;
  }

  /**
   * Gets the value of the 'patientId' field.
   * @return The value of the 'patientId' field.
   */
  public int getPatientId() {
    return patientId;
  }


  /**
   * Sets the value of the 'patientId' field.
   * @param value the value to set.
   */
  public void setPatientId(int value) {
    this.patientId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public com.cbcalla.avrokafkaexample.models.avro.RxStatus getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(com.cbcalla.avrokafkaexample.models.avro.RxStatus value) {
    this.status = value;
  }

  /**
   * Creates a new Rx RecordBuilder.
   * @return A new Rx RecordBuilder
   */
  public static com.cbcalla.avrokafkaexample.models.avro.Rx.Builder newBuilder() {
    return new com.cbcalla.avrokafkaexample.models.avro.Rx.Builder();
  }

  /**
   * Creates a new Rx RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Rx RecordBuilder
   */
  public static com.cbcalla.avrokafkaexample.models.avro.Rx.Builder newBuilder(com.cbcalla.avrokafkaexample.models.avro.Rx.Builder other) {
    if (other == null) {
      return new com.cbcalla.avrokafkaexample.models.avro.Rx.Builder();
    } else {
      return new com.cbcalla.avrokafkaexample.models.avro.Rx.Builder(other);
    }
  }

  /**
   * Creates a new Rx RecordBuilder by copying an existing Rx instance.
   * @param other The existing instance to copy.
   * @return A new Rx RecordBuilder
   */
  public static com.cbcalla.avrokafkaexample.models.avro.Rx.Builder newBuilder(com.cbcalla.avrokafkaexample.models.avro.Rx other) {
    if (other == null) {
      return new com.cbcalla.avrokafkaexample.models.avro.Rx.Builder();
    } else {
      return new com.cbcalla.avrokafkaexample.models.avro.Rx.Builder(other);
    }
  }

  /**
   * RecordBuilder for Rx instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Rx>
    implements org.apache.avro.data.RecordBuilder<Rx> {

    private java.lang.CharSequence rxId;
    private java.lang.CharSequence rxNbr;
    private int patientId;
    private com.cbcalla.avrokafkaexample.models.avro.RxStatus status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cbcalla.avrokafkaexample.models.avro.Rx.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.rxId)) {
        this.rxId = data().deepCopy(fields()[0].schema(), other.rxId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.rxNbr)) {
        this.rxNbr = data().deepCopy(fields()[1].schema(), other.rxNbr);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.patientId)) {
        this.patientId = data().deepCopy(fields()[2].schema(), other.patientId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Rx instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cbcalla.avrokafkaexample.models.avro.Rx other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.rxId)) {
        this.rxId = data().deepCopy(fields()[0].schema(), other.rxId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.rxNbr)) {
        this.rxNbr = data().deepCopy(fields()[1].schema(), other.rxNbr);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.patientId)) {
        this.patientId = data().deepCopy(fields()[2].schema(), other.patientId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'rxId' field.
      * @return The value.
      */
    public java.lang.CharSequence getRxId() {
      return rxId;
    }


    /**
      * Sets the value of the 'rxId' field.
      * @param value The value of 'rxId'.
      * @return This builder.
      */
    public com.cbcalla.avrokafkaexample.models.avro.Rx.Builder setRxId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.rxId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'rxId' field has been set.
      * @return True if the 'rxId' field has been set, false otherwise.
      */
    public boolean hasRxId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'rxId' field.
      * @return This builder.
      */
    public com.cbcalla.avrokafkaexample.models.avro.Rx.Builder clearRxId() {
      rxId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'rxNbr' field.
      * @return The value.
      */
    public java.lang.CharSequence getRxNbr() {
      return rxNbr;
    }


    /**
      * Sets the value of the 'rxNbr' field.
      * @param value The value of 'rxNbr'.
      * @return This builder.
      */
    public com.cbcalla.avrokafkaexample.models.avro.Rx.Builder setRxNbr(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.rxNbr = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'rxNbr' field has been set.
      * @return True if the 'rxNbr' field has been set, false otherwise.
      */
    public boolean hasRxNbr() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'rxNbr' field.
      * @return This builder.
      */
    public com.cbcalla.avrokafkaexample.models.avro.Rx.Builder clearRxNbr() {
      rxNbr = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'patientId' field.
      * @return The value.
      */
    public int getPatientId() {
      return patientId;
    }


    /**
      * Sets the value of the 'patientId' field.
      * @param value The value of 'patientId'.
      * @return This builder.
      */
    public com.cbcalla.avrokafkaexample.models.avro.Rx.Builder setPatientId(int value) {
      validate(fields()[2], value);
      this.patientId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'patientId' field has been set.
      * @return True if the 'patientId' field has been set, false otherwise.
      */
    public boolean hasPatientId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'patientId' field.
      * @return This builder.
      */
    public com.cbcalla.avrokafkaexample.models.avro.Rx.Builder clearPatientId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public com.cbcalla.avrokafkaexample.models.avro.RxStatus getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.cbcalla.avrokafkaexample.models.avro.Rx.Builder setStatus(com.cbcalla.avrokafkaexample.models.avro.RxStatus value) {
      validate(fields()[3], value);
      this.status = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.cbcalla.avrokafkaexample.models.avro.Rx.Builder clearStatus() {
      status = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Rx build() {
      try {
        Rx record = new Rx();
        record.rxId = fieldSetFlags()[0] ? this.rxId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.rxNbr = fieldSetFlags()[1] ? this.rxNbr : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.patientId = fieldSetFlags()[2] ? this.patientId : (java.lang.Integer) defaultValue(fields()[2]);
        record.status = fieldSetFlags()[3] ? this.status : (com.cbcalla.avrokafkaexample.models.avro.RxStatus) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Rx>
    WRITER$ = (org.apache.avro.io.DatumWriter<Rx>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Rx>
    READER$ = (org.apache.avro.io.DatumReader<Rx>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.rxId);

    if (this.rxNbr == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.rxNbr);
    }

    out.writeInt(this.patientId);

    out.writeEnum(this.status.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.rxId = in.readString(this.rxId instanceof Utf8 ? (Utf8)this.rxId : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.rxNbr = null;
      } else {
        this.rxNbr = in.readString(this.rxNbr instanceof Utf8 ? (Utf8)this.rxNbr : null);
      }

      this.patientId = in.readInt();

      this.status = com.cbcalla.avrokafkaexample.models.avro.RxStatus.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.rxId = in.readString(this.rxId instanceof Utf8 ? (Utf8)this.rxId : null);
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.rxNbr = null;
          } else {
            this.rxNbr = in.readString(this.rxNbr instanceof Utf8 ? (Utf8)this.rxNbr : null);
          }
          break;

        case 2:
          this.patientId = in.readInt();
          break;

        case 3:
          this.status = com.cbcalla.avrokafkaexample.models.avro.RxStatus.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










