/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cbcalla.avrokafkaexample.models.avro;
@org.apache.avro.specific.AvroGenerated
public enum RxStatus implements org.apache.avro.generic.GenericEnumSymbol<RxStatus> {
  ACTIVE, CANCELLED, TRANSFERRED, ON_HOLD, DEACTIVATED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RxStatus\",\"namespace\":\"com.cbcalla.avrokafkaexample.models.avro\",\"symbols\":[\"ACTIVE\",\"CANCELLED\",\"TRANSFERRED\",\"ON_HOLD\",\"DEACTIVATED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
